### ISSUE TITLE
Make a list of project-specific content guides

### ISSUE THREAD

**Issue by brittag** [18F/content-guide#108]
As content designers we sometimes build project-specific guides based on the specific needs of the project and the staff on the project. Let's collect examples of these somewhere in our 18F Content Guide.

For example:
- [cloud.gov guide](https://github.com/18F/cg-product/blob/master/ContentGuide.md) that addresses some technical writing topics very specific to that project.

**Comment by awfrancisco** [comment]
Not sure if this is still accurate, but @kategarklavs and I made a [performance profile guide](https://docs.google.com/document/d/1z6oyBG43c-5PkK9rAvWeK_bI0ojQqZIJCt8VcmsW53U/edit)

**Comment by kategarklavs** [comment]
And @jeanninehunter and I created a USCIS-specific guide.

**Comment by nicoleslaw** [comment]
Should this be an internal list or part of the public guide? Asking because some of these are GSA-only audiences.

**Comment by awfrancisco** [comment]
Hm, could it be a mix? With the private links having that same little icon as they do in the handbook? Unless the existence of guide is private (like login.gov since it isn't launched/named) and then we should leave it off.

**Comment by nicoleslaw** [comment]
One more for EITI: https://github.com/18F/doi-extractives-data/wiki/Content-guide

Maybe this topic is worth incorporating in the [upcoming] Design Wiki and then cross-linking in the Content Guide?

**Comment by jeanninehunter** [comment]
Think also applicable is the recently launched login.gov playbook shepherded by @RyanSibley. It features identity management principles for accessing government services:
https://pages.18f.gov/identity-playbook/

**Comment by coreycaitlin** [comment]
I shared the EITI one with Mannie earlier this week for inclusion in the design wiki, with this little write-up:

> The EITI project has some highly technical language and very specific communications constraints. The content guide helps us use terms consistently and avoid retreading debates about language, as well as pushing us to keep things understandable for non-expert users.

**Comment by tadhg-ohiggins** [comment]
We have a number of links, and consensus that we should collect them somewhere, so we should:
- [x] Decide where in the content guide they should go.
- [ ] Add them to that spot.

Adding this to the agenda for the 2016-09-28 guild meeting to finalize a decision on where they should go.

**Comment by coreycaitlin** [comment]
Seems like this belongs under `Content types` (so meta!), and could use a page about the when, why, and how of developing a content guide for your work.

**Comment by nicoleslaw** [comment]
Rounding up the content guides here for myself:

- [Natural Resources Revenue Data](https://github.com/18F/doi-extractives-data/wiki/Content-guide)
- [FBI Crime Data Explorer](https://github.com/18F/crime-data-explorer/wiki/Content-Guide)
- [cloud.gov](https://github.com/18F/cg-product/blob/master/ContentGuide.md)
- [login.gov](https://github.com/18F/identity-private/wiki/Content-Style-Guide)

**Comment by annahsgraves** [comment]
@nicoleslaw I'd love to scrub in on this with you - I can probably pull together a CPS project-wide inventory of content guides from our engagement managers pretty easily. Let me know what you think.

**Comment by nicoleslaw** [comment]
@annahsebok Sounds great, I will set up some time for us!

**Comment by nicoleslaw** [comment]
@kategarklavs Can you share the link to the USCIS guide?

**Comment by nicoleslaw** [comment]
Drafting here: https://docs.google.com/document/d/1w6yPN27cjJsJiYH9jLyx30bvT98zLqegT0oKvygazc8/edit#

**Comment by jeanninehunter** [comment]
@nicoleslaw Here's a link to the doc that influenced the USCIS guide, https://docs.google.com/document/d/1s7UFFCaJrBTCVe90iL4d3EhR53-8-pdYPR8wdVRD0DY/edit?ts=568c2d73, but @kategarklavs might have more up-to-date info on this.

**Comment by nicoleslaw** [comment]
This draft is ready for comments and review!
