### ISSUE TITLE
Question about FAQs

### ISSUE THREAD

**Issue by wslack** [18F/content-guide#11]
From previous work, I think an FAQ is sometimes super useful as a place to publicly track questions received and answers given via e-mail, which can then be moved en masse during a content sprint. An FAQ becomes a more public issues list, for example.

**Comment by emileighoutlaw** [comment]
I think you're right that there are a few instances where an FAQ is the best format for information. But, in general, those are exceptions to a larger rule that FAQs often mask poor content design and strategy. And I think our goal for this guide is to illuminate best practices, acknowledging that there are exceptions to every rule. We aren't prescriptivists, after all! :)

**Comment by wslack** [comment]
> exceptions to a larger rule that FAQs often mask poor content design and strategy

Agreed. If you don't clear out the material in an FAQ, it's not working correctly. The impression I get from the current text is "don't have FAQs and fix problems as they come up" 

> If you find yourself contemplating an FAQ, instead consider going to the places in your website that are generating questions and rethinking how you can alter that content or design to solve the question.

I guess my sentiment is that this feels pretty prescriptive (but is also a tall order), hence the suggest of an alternate strategy for some situations.

**Comment by emileighoutlaw** [comment]
For what it's worth, our FAQ section has probably gotten the most positive feedback of any section in the guide. Bad FAQs abound — they're a systemic content problem.

More importantly, we'd rather err on the side of scaring away one or two valuable FAQs to avoid exponentially more bad ones. A utilitarian approach, if you will.

And if _you_ ever think we need to add an FAQ to our site content, our team will be happy to discuss it with you.

**Comment by wslack** [comment]
> More importantly, we'd rather err on the side of scaring away one or two valuable FAQs to avoid exponentially more bad ones.

Makes sense!
