### ISSUE TITLE
Washington, DC is the way to be

### ISSUE THREAD

**Issue by leahbannon** [18F/content-guide#116]
I propose a change to our style guide to remove the periods from "Washington, D.C." This is the way that the people of DC prefer, as is evident on [dc.gov](http://dc.gov).

Preferring to use the naming conventions that the people of a country or city prefer is [OpenStreetMap](https://www.openstreetmap.org)'s policy, called the [On the Ground Rule](https://wiki.openstreetmap.org/wiki/Disputes#On_the_Ground_Rule). (OpenStreetMap is an enormous and awesome open source project that has created a free map of the world for you and me.) I think this is generally a great policy that we should fork. The rule states:

> If the dispute cannot be resolved through discussion, then the simple default rule is whatever name, designation, etc are used by the people on the ground at that location are used in the non-localized tags.

❤️

**Comment by vdavez** [comment]
I completely endorse this proposal without any reservation.

**Comment by nicoleslaw** [comment]
(Summarizing my comments from Slack here.)

Changing to the postal code model may confuse people with other entries like `U.S.` That said, I don’t have a preference. Since we are usually writing for screens and mobile readers, I think the periods add characters more than anything.

I am more familiar with Chicago style than AP, and they go with `DC` as briefly noted [here](http://www.chicagomanualofstyle.org/qanda/data/faq/topics/Abbreviations/faq0048.html). They have a separate rule about `US`:

```
In running text, spell out United States as a noun; reserve US for the adjective form only (in which position the abbreviation is generally preferred). See also 10.4.

US dollars
US involvement in China
but
China’s involvement in the United States
```

**Comment by jameshupp** [comment]
My comments, summarized similarly, which have led me to lean toward dropping the periods:
1. AP Style no longer abbreviates state names, which was done in a style that used periods. That meant `D.C.` was the parallel choice, but that style is no longer a thing that exists.
2. We as an organization usually choose to use the terms people use for themselves. I don't know any polling from the District on this point, but the elected government of the District is a reasonable proxy in the absence of other information, and they use `DC`.
3. An exception to the above might be if it would cause confusion, either as a matter of comprehension or of law. I just can't see any circumstance in which `D.C.` will be clear but `DC` will be confusing. (This was not on Slack, but it seems relevant.)
4. There aren't any parallels to the District of Columbia in other aspects of local/state governing in the United States. I'm not sure we have to worry about being consistent with other things.

**Comment by tadhg-ohiggins** [comment]
+1, but then I'm generally in favor of getting rid of the periods in initialisms.

**Comment by nicoleslaw** [comment]
cc @kategarklavs @emileighoutlaw @awfrancisco Do y'all have a sense of next steps on this? Let me know if I can help.

**Comment by emileighoutlaw** [comment]
Thanks for the ping, and great question. I think we have enough consensus to change the style guide— I can do that now. 

How the style guide change impacts the work we've already published on 18f.gsa.gov is (I think) a question for @awfrancisco 

Should we also announce the change in #g-content / other channels?

**Comment by awfrancisco** [comment]
Unclear how this will change existing content. I'll chat with the site team about it. And yeah, I think we should announce it in #g-content, and probably #dc too
