### ISSUE TITLE
Create a CONTRIBUTING.md file with voting rules

### ISSUE THREAD

**Issue by andrewmaier** [18F/content-guide#117]
I believe the content guild is using a fancy voting system to approve substantive additions/changes to the content guide. Can you detail this process in the repo? (I'm selfishly asking because I'd like to borrow this for the research guild's documentation.)

**Comment by emileighoutlaw** [comment]
To add something to the effect:
1. An 18F team member files an issue asking for a vote to change a rule
2. Guild members emoji vote thumbs up or thumbs for ~5 business days
3. Discuss results results at guild meeting and implement a change (if necessary)
