### ISSUE TITLE
Duplicate info about conciseness

### ISSUE THREAD

**Issue by nicoleslaw** [18F/content-guide#129]
Need to combine these:

https://pages.18f.gov/content-guide/structure-the-content/#keep-sentences-short-and-sweet

https://pages.18f.gov/content-guide/be-concise/ - if we keep this, we should give credit to GDS for it

**Comment by kategarklavs** [comment]
+1 to crediting GDS for the "Be concise" content.

In terms of combining, what are you thinking? (I like the idea of keeping the "short & sweet sentences" as a subcategory of the larger "concision" section — for example, "One way to ensure you're writing concisely on the whole is to keep your sentences short and sweet. We recommend keeping sentences to 25 words or fewer, except when absolutely necessary ... " etc.)

**Comment by nicoleslaw** [comment]
@kategarklavs You read my mind! I was thinking this short & sweet part should move over so it's easier to find.

**Comment by kategarklavs** [comment]
We are of one mind(!) (And that sounds good!)

**Comment by emileighoutlaw** [comment]
Assigning myself to this issue! PR forthcoming
