### ISSUE TITLE
Add accessibility guidance for the naming of links

### ISSUE THREAD

**Issue by toolness** [18F/content-guide#131]
I can't seem to find any guidance in the content guide on this, so I figured I'd mention it here.

Basically, screen reader users often "skim" content by skipping from one link to another.  This becomes difficult when links are called things that don't make sense out of context. Examples include "click here" and "learn more", which are quite common, so one best practice is to try to name links so that they make sense out of context.

e.g., instead of:

> [Click here](#) for more information about our Code of Conduct.

prefer:

> For more information, see the [18F Code of Conduct](#).

Would this be appropriate for the content guide?  I noticed it doesn't seem to be in the [18F Accessibility Guide](https://pages.18f.gov/accessibility/) either.

If it is appropriate for the content guide, I'm not sure where the best place for it is--right now the only place it seems like it _might_ belong is the [Links and additional resources](https://pages.18f.gov/content-guide/technical-and-interface-writing/#links-and-additional-resources) section of the Technical and interface writing page, except that the naming of links isn't just about technical writing.

**Comment by tadhg-ohiggins** [comment]
I meant to include this in the URLs and filenames section, so it might fit in that section.

**Comment by toolness** [comment]
Cool, do you want me to try to draft a section on this?

Also just found a recent post on [making accessible links](https://www.sitepoint.com/15-rules-making-accessible-links/) which has some other suggestions beyond this one, many of which are content-related.

**Comment by emileighoutlaw** [comment]
Not to co-opt this conversation, but I have been wondering about button copy that says things like "Learn more," which is a pattern we use on betaFEC. For example:

<img width="758" alt="screen shot 2016-09-06 at 10 29 37 am" src="https://cloud.githubusercontent.com/assets/10552702/18279911/dd48b2ae-741c-11e6-9e9b-6e536ce21db3.png">
_https://beta.fec.gov/registration-and-reporting/_

Is that also bad practice for accessibility? And if so, any ideas what might be better?

**Comment by nicoleslaw** [comment]
When we did the IA workshop recently, we talked about having a section on links and SEO (search engine optimization). Let me know if you think that makes sense...happy to help!

**Comment by tadhg-ohiggins** [comment]
Something not mentioned here that I also like: for `a` elements to have `title` attributes, and for those to have the title of the linked resource as their value.
So if I'm writing:

> There is a tricky words section in the content guide

And I want to make “a tricky words section” into a link, the output HTML should be:

``` html
There is <a href="https://pages.18f.gov/content-guide/specific-words-and-phrases/" title="Specific Words and Phrases">a tricky words section</a> in the content guide
```

That way, hovering over the link provides extra information about the link target, and I hope/assume that more advanced screen readers would also make that information available to users if it's present.

**Comment by toolness** [comment]
Good question!

@tadhg-ohiggins' guidance is good but it only _partially_ works with VoiceOver: when tabbing through the page, it first announces the link text and then announces the `title` after a short pause, which is great.  However, when using VoiceOver's **List links on page** mode (<kbd>Ctrl</kbd>+<kbd>Option</kbd>+<kbd>U</kbd>), we only see and hear the link text. 😞 

In these kinds of situations I tend to use [WebAIM's CSS for positioning content off-screen](http://webaim.org/techniques/css/invisiblecontent/#absolutepositioning) to add extra context to the link text that screen reader users (and search engines) will read but sighted users won't see, e.g.:

``` html
<a href="https://beta.fec.gov/registration-and-reporting/essentials-house-and-senate-candidates-and-committees/">
  Learn more
  <span class="hidden">about candidates and candidate committees</span>
</a>
```

I'm curious if @nickbristow (or anyone else) has any other suggestions, though!

**Comment by nickbristow** [comment]
@toolness not a huge fan of `title`. It's a pain for screen readers to access. I like the `sr-only` content added in the link or aria. Just gotta be careful with aria, it usually overwrites default value to SR's.

**Comment by rtwell** [comment]
stumbled upon this and i _think_ this may be the issue to mention it: http://webaim.org/techniques/hypertext/link_text

just my 2¢

**Comment by jameshupp** [comment]
@rtwell  This is great! Thanks!

**Comment by toolness** [comment]
Nice, that is the resource I was looking for when I first wrote this issue, but couldn't find it for some reason. Thanks @rtwell!

**Comment by toolness** [comment]
Ok, I've got a draft of this section up on Google Docs:

https://docs.google.com/document/d/1L_ug6MiaXUTH7fiN-9g07OOFJVW674U4x-6V3TkQgK0/edit#heading=h.tizuhp461r1l

Comments are welcome.

Once we've got a general consensus on the content, I can issue a PR!

**Comment by nickbristow** [comment]
👍

**Comment by nicoleslaw** [comment]
Added some comments. Thanks so much for putting this together! 👏
