### ISSUE TITLE
New guidance: kanban, not Kanban

### ISSUE THREAD

**Issue by awfrancisco** [18F/content-guide#137]
Thoughts? Arrived at this after a discussion with @abrouilette

**Comment by abrouilette** [comment]
Lowercase-k is correct. "Kanban" is not a proper noun.

**Comment by kategarklavs** [comment]
I am in favor of not capitalizing improper nouns! (Well, not improper — you know what I mean: regular nouns.)

**Comment by awfrancisco** [comment]
Closed by #139
