### ISSUE TITLE
Add a section about forms/data entry

### ISSUE THREAD

**Issue by toolness** [18F/content-guide#138]
I noticed that the content guide doesn't have a section on forms or data entry.

I'm currently reading through the second edition of Aaron Gustafson's [Adaptive Web Design](http://adaptivewebdesign.info) and noticed he had the following to say about it (page 47):

> ![adaptive-web-design-2nd-ed-page-47](https://cloud.githubusercontent.com/assets/124687/18518102/a4bb8668-7a6c-11e6-845e-66a7890d53aa.png)

Is this advice something the content guild agrees with?

**Comment by coreycaitlin** [comment]
Thanks for raising this @toolness! We discussed in the content guild — notes below.

Notes from Content Guild discussion on this:

- User research is super, super important for forms — any guidance should stress this!
- We do agree with this advice broadly, but this might raise a larger question about whether we need a new section on forms. That said, the way we approach forms is pretty much the same way we approach any kind of content: do research, be user-centered, iterate based on feedback.
- A small section in the "Interface writing" section could help.
- Sometimes you don't need to use full-sentence questions — i.e. on mobile, `Email` can work as well or better than `What is your email address?` Choices here depend on goals.
- +1 to testing for specific context and users
- We probably have some strong opinions about forms we could gather in another session.

Many thanks to @RyanSibley @kategarklavs @nicoleslaw for these thoughts.

**Comment by coreycaitlin** [comment]
Huzzah, this is done! 🎉 many thanks to @kategarklavs and @toolness and everyone else who reviewed and helped!
