### ISSUE TITLE
How should we capitalize scrum?

### ISSUE THREAD

**Issue by kategarklavs** [18F/content-guide#140]
Per our 9/14/16 content guild meeting, we'd like to agree on an official 18F capitalization of scrum — let's discuss!

**Comment by awfrancisco** [comment]
I vote `Scrum`.

I have the same questions about `Lean Startup` as well.

**Comment by kategarklavs** [comment]
@awfrancisco I agree with `Scrum`. (And I don't yet have a strong opinion about `Lean Startup`, but I'll do some research to formulate an opinion.)

**Comment by jameshupp** [comment]
I vote `Scrum` when referring to the total set of practices that make up the specific agile method, `scrum` for individual standup meetings that take place within that method. So a `Scrum team` and `Scrum board` but a `daily scrum`. That way, scrums are distinct from the Scrum that they are part of.

@awfrancisco Unless you are referring to an event directly related to the trademark owned by Eric Ries, I'm fairly sure it should be `lean startup`. I can get into why (it has to do with the difference between trademark and copyright, primarily), but I don't want to distract from the main thrust of this issue. If anyone wants to discuss let's open a separate issue.

**Comment by jameshupp** [comment]
I suppose to be even clearer, we could just declare that at 18F we never refer to a daily standup as a `scrum` and say it's always capitalized.
