### ISSUE TITLE
Move content about link text to its own section?

### ISSUE THREAD

**Issue by tadhg-ohiggins** [18F/content-guide#148]
Currently it's part of the URLs and filenames section: https://pages.18f.gov/content-guide/urls-and-filenames/#link-text

I think it should probably be its own section.

**Comment by coreycaitlin** [comment]
Agreed — this content [link text through screenreader-only text] is useful for people who may be writing content, as well as folks who are naming files/URLs. This new section should also link to the accessibility guide.

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
