### ISSUE TITLE
Citizen

### ISSUE THREAD

**Issue by awfrancisco** [18F/content-guide#15]
Add guidance around using the word "citizen" as a generic term for people who live inside the U.S. Many government services serve non-citizens and individuals with various immigrations/visa statuses. 

Could go in Conscious style section?

**Comment by awfrancisco** [comment]
Add exception for citizen-only services.

**Comment by emileighoutlaw** [comment]
+1,000 to this. In newspaper, we always said "Iowa City residents" to be inclusive, but I think the term "resident" has specific legal meaning. Any ideas on what broad term we might use?

**Comment by awfrancisco** [comment]
Public? Americans?

**Comment by kategarklavs** [comment]
@emileighoutlaw Some projects use "public" (especially when it's not known whether the reading audience will include only citizens).

**Comment by emileighoutlaw** [comment]
+1 to public!

**Comment by melodykramer** [comment]
https://github.com/18F/content-guide/pull/36 addresses this.
