### ISSUE TITLE
Missing package.json?

### ISSUE THREAD

**Issue by hbillings** [18F/content-guide#154]
I'm looking to adapt your lovely redesign for the front-end guild's guide. :) I tried following the `README` to get this set up locally, but `npm` complains that there is no `package.json` to install dependencies from. Are the instructions in the `README` out of date, or should I be looking for the `package.json` elsewhere?

**Comment by emileighoutlaw** [comment]
Pinging our more technical guild members! @tadhg-ohiggins and @toolness — any idea how to help?

Also, apologies for the delay @hbillings— do you still need an answer on this?

**Comment by toolness** [comment]
Oh, I think the README is now out of date? We don't seem to be using a bunch of tools mentioned in the **Running the site** section:

> The 18F Content Guide runs on [Jekyll](http://jekyllrb.com/). To run it locally:
>
> 1. Clone the repository.
> 1. Get [Jekyll] and the necessary dependencies: `bundle install`
> 1. Install all node dependencies: `npm install`
> 1. Set the $NODE_ENV to `dev`: `export NODE_ENV=dev`
> 1. Package js files with webpack: `webpack --watch`
> 1. Run the web server: `npm run start` (or `jekyll serve` if you have Jekyll installed globally)
> 1. Visit the local site at [http://localhost:4000](http://localhost:4000)

Specifically, steps 3-6 seem to be completely inaccurate; at some point in the past, the content guide might have used `npm` and `webpack`, but it doesn't seem to anymore. Maybe that section should be replaced with something like this:

> The 18F Content Guide runs on [Jekyll](http://jekyllrb.com/). To run it locally:
>
> 1. Clone the repository.
> 1. Get [Jekyll] and the necessary dependencies: `bundle install`
> 1. Run `./go serve`.
> 1. Visit the local site at [http://localhost:4000](http://localhost:4000)

Thoughts @tadhg-ohiggins ?

**Comment by hbillings** [comment]
Ha, yeah, I actually wrote up a fix to the `README` to reflect what @toolness wrote in the comment above, and then I never filed the PR. >_<

**Comment by toolness** [comment]
Hehe. :)  Do you still have that fix on your machine?  If not, I'm happy to change the README and issue a PR.

**Comment by emileighoutlaw** [comment]
Can we close this, @hbillings @toolness ?

**Comment by toolness** [comment]
Hmm, I think we should definitely resolve it first--the README instructions were understandable confusing for @hbillings because they're so out of date. I'll submit a PR to fix it this week!
