### ISSUE TITLE
Link out to (or embed) Google/Udacity accessibility videos

### ISSUE THREAD

**Issue by toolness** [18F/content-guide#161]
I've been going through [Google/Udacity's Accessibility course](https://classroom.udacity.com/courses/ud891) and it's really great. While it's advertised as being for "advanced developers", so far a lot of it is still quite useful to folks with basic knowledge of HTML.

In particular, there are a few videos that could be useful to link-out to from the content guide:

* [Navigating with a screen reader](https://www.youtube.com/watch?v=Oo4HoeL6yIE) in [Lesson 4](https://classroom.udacity.com/courses/ud891/lessons/8079270944/concepts/81639702060923#) (7 mins) introduces VoiceOver and shows how people use its Web Rotor to quickly navigate through documents via their headings.

* [Other navigational options](https://www.youtube.com/watch?v=kqbOBl1jP90) (4 mins) shows how people use VoiceOver's Web Rotor to quickly find the links and form controls they're looking for in documents. It also covers how screen reader users deal with mis-pronounced words, and how they are able to dive into text to determine how individual words are spelled. Based on this, the narrator provides advice for content writers.

If this kind of thing sounds useful, I'm happy to submit a PR.

**Comment by emileighoutlaw** [comment]
Hey Atul! Thanks for posting this. We think this might have a better home in the 18F Accessibility Guide. Would you be willing to open an issue about this in their repo?

Additionally, we'd be happy to explore ways to build pathways from our Content Guide (perhaps from our accessible links guidance) to the Accessibility Guide.

**Comment by toolness** [comment]
That sounds good--I'll talk to the other folks in the accessibility guild about figuring out how best to integrate this content, and make sure there are pathways between it and other guides like the Content Guide!
