### ISSUE TITLE
Review 18F Pages content

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/content-guide#163]
In the 18F Pages migration to Federalist, we're deprecating some content-specific pages. We should take a look at those pages and see if there's anything we want to incorporate into our Content Guide.

https://pages.18f.gov/edu-measure-content
https://pages.18f.gov/edu-voice-and-tone
https://pages.18f.gov/g-content
https://pages.18f.gov/plain-language-tutorial
https://pages.18f.gov/18F-plain-language-tutorial

**Comment by coreycaitlin** [comment]
Decision checklist:

- [x] https://pages.18f.gov/edu-measure-content - issue open to move this into the content guide: #8 
- [x] https://pages.18f.gov/edu-voice-and-tone - already in the content guide; #164 adds the resources, which was the only outstanding section not incorporated
- [x] https://pages.18f.gov/g-content
- [x] https://pages.18f.gov/plain-language-tutorial
- [x] https://pages.18f.gov/18F-plain-language-tutorial - this was an alternate version of `plain-language-tutorial`, which likely got orphaned when we renamed the repo

**Comment by kategarklavs** [comment]
We've decided we don't need to incorporate stuff from the g-content page.

**Comment by coreycaitlin** [comment]
Let's rescue the Plain Language Tutorial, if possible! I'll ping Jez.
