### ISSUE TITLE
Guidance about sunsetting content

### ISSUE THREAD

**Issue by coreycaitlin** [18F/content-guide#166]
We should write up some of how we think about sunsetting content, the concerns and questions that come up in that process, and how to take care of users in the process of retiring content responsibly.

**Comment by nicoleslaw** [comment]
I posted some references in the channel starting here: https://gsa-tts.slack.com/archives/g-content/p1488404362000730

**Comment by coreycaitlin** [comment]
Relevant links from @nicoleslaw:

- [Best practices for archiving and deleting content](http://www.contentstrategyinc.com/best-practices-for-archiving-and-deleting-content/)
- [How Should You Handle Expired Content?](https://moz.com/blog/how-should-you-handle-expired-content)
- [Withdrawing and unpublishing content, and labelling content from previous governments](https://www.gov.uk/guidance/content-design/gov-uk-content-retention-and-withdrawal-archiving-policy)
- [Unpublishing and withdrawing ('archiving')](https://www.gov.uk/guidance/how-to-publish-on-gov-uk/unpublishing-and-archiving)

**Comment by awfrancisco** [comment]
Email I sent in response to the initial question that we could use as a place to start. (I also included the links above)

> 
> I posed your question to our team of content designers, and while they didn't have a go-to checklist for sunsetting content, they did have a couple ideas. As an overarching principle - if you really have to make content go away, give users a path to find what they need. This could include
> 
> - URL redirects
> - Ceding ownership of the content to another organization who can maintain it
> - Keeping content around and adding context that it is depreciated or no longer maintained
> - Archiving services can pull a full archive of content and make it available elsewhere
> - Custom 404 pages to help users find what they're looking for
>

**Comment by nicoleslaw** [comment]
I can take this.

**Comment by coreycaitlin** [comment]
This could go under "our approach," at least at first, but we aren't sure what to call the page!

**Comment by nicoleslaw** [comment]
Thinking out loud here... What do you think about the subsection being `Keep refining` and then we have a place to talk about governance and [ongoing testing](https://github.com/18F/content-guide/issues/8)?

**Comment by kategarklavs** [comment]
@nicoleslaw I really like this idea (especially because we don't have a testing section, though I know the team had discussed putting one together). And I also like it because refining content seems much less harsh than sunsetting, necessary though sunsetting sometimes is ...

**Comment by nicoleslaw** [comment]
Started a draft here: https://docs.google.com/document/d/1XMtAQf_qd1ORVDQ2aVCJ4JtCfMKnv5a95X-86IIChhM/edit#

cc @kategarklavs as it relates to #8

I will add more to the intro and the second section, but I'm curious if this feels like a solid rough take?

**Comment by kategarklavs** [comment]
@nicoleslaw Howdy! I'm happy to take a look this week (today or tomorrow) 🎉

**Comment by nicoleslaw** [comment]
This is ready for a final review/editing pass: https://docs.google.com/document/d/1XMtAQf_qd1ORVDQ2aVCJ4JtCfMKnv5a95X-86IIChhM/edit

**Comment by coreycaitlin** [comment]
This looks great! I think we should get this moved into a PR!
