### ISSUE TITLE
Add info from Federalist content guide

### ISSUE THREAD

**Issue by line47** [18F/content-guide#167]
There is content on the federalist site for how to write content that is not on the 18F Content Guide site. I think it would be beneficial to have all the content guidelines on the 18F Content Guide and move the following pages from the federalist docs to the content guide and reference them there.
This would give one source of truth for content.

- [Content guide](https://federalist-docs.18f.gov/pages/content-guide/)
- [Writing content for your homepage](https://federalist-docs.18f.gov/pages/content-guide/writing-content-for-your-federalist-homepage/)
- [Writing about your team](https://federalist-docs.18f.gov/pages/content-guide/best-practices-for-writing-who-we-are/)
- [Writing about your research](https://federalist-docs.18f.gov/pages/content-guide/best-practices-for-writing-what-we-do/)
- [Writing clear contact forms](https://federalist-docs.18f.gov/pages/content-guide/contact-forms/)

**Comment by emileighoutlaw** [comment]
Hello there! Great to hear from you!

Our Content Guild chatted about this at our meeting, and we feel much of this guidance is very specific to Federalist templates, whereas the 18F Content Guide is more general guidance for writers and editors working in any system or template. 

We do think the Federalist documentation could use some help from a content designer, including the use cases, mission, and home for the content. If Federalist has the budget for content design, we'd be excited to work on this with the Federalist team!

**Comment by coreycaitlin** [comment]
Sounds like one path forward could be to integrate some guidance based on the Federalist content guide into a "common content types" section of the 18F content guide. (Especially the guidance on clear contact forms.)

**Comment by brentryanjohnson** [comment]
It looks like the Federalist team removed content guidance, and now links to the 18F content guide.
