### ISSUE TITLE
Add DevOps on the specific words and phrases page?

### ISSUE THREAD

**Issue by jamiealbrecht** [18F/content-guide#169]
Hi, 

I was working on a #writinglab issue and the word DevOps made me pause. I looked it up in the content guide and was sad when it wasn't there. Let's add it?

<3jme

**Comment by nicoleslaw** [comment]
I agree, but I have one question: Do we use the term publicly, or is it more of an in-house team term? (It is an industry standard, but I am not sure if we use it in blog posts, etc.)

**Comment by coreycaitlin** [comment]
Yes! it's a blog tag.

**Comment by kategarklavs** [comment]
Word — taking this on now ⭐️

**Comment by kategarklavs** [comment]
Just created a PR — closing this!
