### ISSUE TITLE
User Centered Design et al

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/content-guide#17]
user centered design? Or user-centered design? Same for human-centered design. And human-computer interaction (caps? hyphen?)

Seems in the same vein as open source software.

**Comment by emileighoutlaw** [comment]
Although wikipedia: https://en.wikipedia.org/wiki/User-centered_design

**Comment by awfrancisco** [comment]
I'd go hyphen on all of these, though I don't think we need to include human-computer interaction in the guide. How often does that come up?

**Comment by kategarklavs** [comment]
+1 to user-centered design and human-centered design. (And, if we were to use it, I'd vote in favor of human-computer interaction vs. human computer interaction, though I've never actually used this phrase ...)

**Comment by emileighoutlaw** [comment]
Human-computer interaction is a field of research, so I think it might come up in technology writing — if not for us, definitely for people who might look to us for guidance.

https://en.wikipedia.org/wiki/Human%E2%80%93computer_interaction

**Comment by awfrancisco** [comment]
I still think that's a little obscure for us. And the correct answer, human-computer interaction, is not an abnormal construction, so I don't think we need to include it.
