### ISSUE TITLE
Selecting the file format of your web content 

### ISSUE THREAD

**Issue by skorasaurus** [18F/content-guide#170]
I am not sure if this is germane to this guide (maybe the accessibility guide is better?) to but I was wondering if you have best practices or determinants whether to publish certain content as PDFs or as HTML.

**Comment by coreycaitlin** [comment]
@skorasaurus Thanks for contributing! We would love to add a page about best practices around HTML, and when PDF is appropriate.

We may decide to incorporate this guidance into a page about making content flexible (for mobile, printing, or other needs). Would that be helpful for this kind of decision? Are there specific questions or concerns you've needed to address in making this choice?

**Comment by skorasaurus** [comment]
(content flexibility) Yes! I'm a Web developer at the Cleveland Public Library and manage our Web Content/information structure on our site ; looking forward to learn more about criteria, standards, best practices of how library information (like policies, procedures, and other information that tends to be stored at pages named "about the library") should be disseminated online and accessible to our patrons.

Also interested to learn more nuances about the advantage and disadvantages of the file formats (esp. Word vs. Pdf vs html) especially regarding accessibility, balancing this information with the constraints of our limited staff capacity; and changing our workflows to follow any decisions made on the file formats. 

I'm also considering how to determine the information that we disseminate via print (flyers on news, programming, events) should be and ensure information that's shared on print is also shared digitally in the most relevant for our patrons. 
I'd be happy to answer any more questions that you have and have found the content and accessibility guides helpful so far (thank to the 18F team) #

**Comment by skorasaurus** [comment]
(was on mobile and unable to make edits; but are now in the parent comment

**Comment by ShawnEklund** [comment]
I'm working a project now and struggling with this same problem-to PDF or not. I ran across Oregon.gov website guidelines that has pretty good rubric for when and why to use a PDF.  http://www.oregon.gov/docs/state_web_guidelines.pdf And yes that is a link to a PDF. Page 8

**Comment by tadhg-ohiggins** [comment]
Corey and I came up with a [draft for internal review (access limited to GSA employees)](https://docs.google.com/document/d/1agN4pQrmL9qS2gCuO82dy67RfAw8Atqq4sL_NjrCIx0/edit).

This will likely become its own page in the content guide once past review.

**Comment by coreycaitlin** [comment]
This page is now live as part of the content guide: [Make content web-friendly](https://content-guide.18f.gov/make-content-web-friendly/). 🎉
