### ISSUE TITLE
Consider adding guidance for Log in, Log-in, Login …

### ISSUE THREAD

**Issue by carodew** [18F/content-guide#18]
I've found this term can be tricky for people, especially when it's used as a noun vs. verb vs. adj.

"I couldn't log in to the website because the log-in page was totes janky." (Or whatever standard you guys decide on.)

Also I've been using this guide since it launched – thanks!

**Comment by kategarklavs** [comment]
@carodew: Thanks for this suggestion! We'll add a section clarifying uses of log in vs. login.

**Comment by awfrancisco** [comment]
What about this for our guidance? To go in the Specific words and phrases section. 

log in as a verb, for example You must log in to access your calendar.
login as a noun, for example I forgot my login name and password.
log-in as an adjective, for example Make sure the log-in page is 508 compliant.

**Comment by carodew** [comment]
@awfrancisco seems clear to me. Do we have an opinion on whether to use log in vs. sign in?

**Comment by awfrancisco** [comment]
Looked at this some more and I think this might be better. Also, I don't think we have a preference on log in vs sign in. 
-   **login** when used as noun, for example, _I forgot my login name and password_, or when used as an adjective, for example _Make sure the login page is 508 complaint._
  - **log in** when used as a verb, for example, _You must log in to access your calendar._
