### ISSUE TITLE
New section: Writing with and about data

### ISSUE THREAD

**Issue by nicoleslaw** [18F/content-guide#187]
- Info about process (gather samples of data, review open data standards, etc.)
- How to phrase sentences with data and frame data limitations
  - Define and describe fields
  - Best ways to publish the files/info (spreadsheet? PDF? etc.)
- General tips on data dictionaries and readmes (cross link to open source guide)

cc @RyanSibley @coreycaitlin — would love your input on the draft after I get something together.

**Comment by RyanSibley** [comment]
No problem. I'd love to help and contribute where I can.

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
