### ISSUE TITLE
New section: Giving and receiving feedback on writing

### ISSUE THREAD

**Issue by jamiealbrecht** [18F/content-guide#191]
I keep forgetting to bring this up in our guild meetings. A number of us wrote a guide to [giving and receiving writing feedback](https://docs.google.com/document/d/1aNECZ1-7FzEW7Fp_MJD8ngoRuEhQYz0wTMkB5AepyV4/edit). 

Should we add it to the content guide?

**Comment by coreycaitlin** [comment]
The consensus is YES, and we think it should go in the "Our Approach" section.

**Comment by jamiealbrecht** [comment]
Filed a pull request. :)

**Comment by kategarklavs** [comment]
@jamiealbrecht Sweet! Want me to review?

**Comment by jamiealbrecht** [comment]
Yes, thank you! I just assigned you. :)

**Comment by nicoleslaw** [comment]
Can we close this out?

**Comment by kategarklavs** [comment]
@nicoleslaw Oh! Yes, I think we can — just checked, and it looks like the PR was merged but we forgot to close this issue 🤦‍♀️
