### ISSUE TITLE
Move to a new CI/CD system

### ISSUE THREAD

**Issue by hollyallen** [18F/content-guide#196]
This repository has been using Travis CI, however access to Travis CI is now turning off. When you need to use this repository again, convert it to a CI/CD system which is in the ITSP such as Circle CI.

**Comment by wslack** [comment]
I think that this repository is just being published with federalist, so imagine that there won't be a need for circle, but defer to the owners for the final call.

**Comment by toolness** [comment]
Thanks! I think @tadhg-ohiggins is working on this in #194. I also believe that the [HTMLProofer](https://github.com/gjtorikian/html-proofer) tool is used during CI to ensure there are no broken links etc in the site, so CI is performing a useful service.

**Comment by tadhg-ohiggins** [comment]
We did use HTMLProofer with Travis. I am working on this, and have run into some ruby/node dependency issues that make it more complicated than I had expected.

**Comment by tadhg-ohiggins** [comment]
Addressed by moving to Circle CI in https://github.com/18F/content-guide/pull/194
