### ISSUE TITLE
Explicitly state use of Trailing slashes in URLs and paths

### ISSUE THREAD

**Issue by skorasaurus** [18F/content-guide#201]
I was wondering about the use of slashes at the end of URLs and paths and went to refer to your [URL and filenames page](https://content-guide.18f.gov/urls-and-filenames). While reading it, I realized that although no rules/guidelines are explicitly mentioned, there are a few rules that are practiced in the document. 

I was wondering if that was intentional and suggest to explicitly state guidelines/usage of trailing slashes. [Following the their trailing slashes' usage as of the latest commit in this writing](https://github.com/18F/content-guide/blob/b41b4bc311d8739c96bf87f7c4d58d7500f88bae/_pages/content-types/urls-and-filenames.md) would cinlude: 
- In both print and on a webpage; omit the slash at the end of a URL when only mentioning a base URL with no subsequent paths (i.e. `gsa.gov`) 
- When there are paths, include the trailing `/`   (i.e. `gsa.gov/content-guide/`) 
- Omit the trailing `/` when referring to files. (i.e. `gsa.gov/content-guide/medicaire-application.pdf`)

**Comment by tadhg-ohiggins** [comment]
Unfortunately, technical considerations (for example, systems that sadly still treat paths with slashes differently from those without) make it difficult to explicitly recommend these approaches. It might be worth adding a section discussing this, which we'll consider. Thanks for the suggestion!

**Comment by brentryanjohnson** [comment]
Closing for now. We may revisit this if research points us to it again!
