### ISSUE TITLE
Updating acronym reference

### ISSUE THREAD

**Issue by jeanninehunter** [18F/content-guide#204]
@qmanderson1 created a [great breakdown](https://docs.google.com/document/d/1vGleN0yTwibTp8ClXcGGiKVxgM8dTewG_IFeErxU-3Y/edit#heading=h.7ckrp99wgurm) of commonly used acronyms in our shop. Thought this info might be useful to add to the guide - especially helpful for new team members. Could add to [existing page](https://content-guide.18f.gov/abbreviations-and-acronyms/) or add a subpage.

Could be a topic for a pair writing session 1:1 between Qituwra and other content strategists or other members of the content guild.

**Comment by nicoleslaw** [comment]
I wonder if you might suggest adding this to the Handbook instead of the Content Guide? https://handbook.18f.gov/glossary/

**Comment by jeanninehunter** [comment]
Thanks, @nicoleslaw, for the suggestion! As long as it appears in a place that's helpful. If it's for the TTS Handbook, then I should close this issue, replacing it with a new GH issue for the handbook, right, @nicoleslaw?

**Comment by jeanninehunter** [comment]
Closing this issue, replacing it with a [new GH issue](https://github.com/18F/handbook/issues/612) for the TTS Handbook.
