### ISSUE TITLE
Inclusive language: encourage people-first language

### ISSUE THREAD

**Issue by coreycaitlin** [18F/content-guide#208]
We got this excellent note via Twitter: https://twitter.com/letterfromflint/status/949356735298457600

We currently encourage this kind of construction in several sections, including the [Ability and disability](https://content-guide.18f.gov/inclusive-language/#ability-and-disability) section, and specify that people should avoid the `the _____s` construction in these spots:

> Use descriptors of gender identity or sexual orientation as modifiers, not as nouns (for example, transgender person, cisgender person, or lesbian woman).

> When referring to a person’s race or ethnicity, use adjectives, not nouns (for example, a Hispanic person, not a Hispanic).

For me, this raises a few questions for the next revision of this page:

1. Should we have a section on socio-economic difference? (Which could offer guidance on things like how to reference homelessness) — see #190 
2. Is "people-first language" a necessary/useful term to introduce at a higher level?
3. Should we pull out the adjective vs. noun guidance and move it to a more general point of guidance? (either in lieu of or in addition to noting in more detailed sections)

**Comment by kategarklavs** [comment]
Ah, these are good questions. I'm in favor of introducing a more general section on people-first language (and can start work on this, if someone would like to pair with me 😁 ).

Re: socio-economic differences: I haven't seen a ton of examples of references to socioeconomic differences in my work here, but I think adding guidance could be helpful. +1 to "person experiencing homelessness" (as homelessness can be a temporary state, and certainly isn't a person's main identifying trait). Maybe we can discuss this further during our next guild meeting? What say other folks?

**Comment by coreycaitlin** [comment]
Whoops! We already had an issue for a section on socioeconomic diversity, thanks to @jamiealbrecht. Added a reference above — it's issue #190

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
