### ISSUE TITLE
User vs. human centered design

### ISSUE THREAD

**Issue by awfrancisco** [18F/content-guide#212]
When 18F talks generally about it's design principles and practice, we often use either `user-centered design` or `human-centered design`. I think we should endorse one phrase as the preferred description for 18F's general design philosophy. This will keep our content consistent and make it less ambiguous. If specific instances or projects call for a more exact phrase, people are free to use and explain alternative design philosophies. 

Would love to hear other people's thoughts and/or votes in the comments.

**Comment by tbaxter-18f** [comment]
+1 for human centered. I like that it's, well, humanistic. And "user-centered" always reminds me of the possibly-apocryphal Tufte quote "There are only two industries that call their customers ‘users’: illegal drugs and software"

**Comment by abbeykos** [comment]
+1 for human centered as well. Also, Google Trends supports HCD over UCD (with a growing gap): 
<img width="1107" alt="screen shot 2018-05-24 at 4 49 24 pm" src="https://user-images.githubusercontent.com/38867175/40513015-8a35c1fe-5f72-11e8-9116-c81632d40a45.png">

**Comment by kategarklavs** [comment]
Hey! Repeated from yesterday's meeting (but commenting here so the thought isn't lost) – for the reasons other folks cited, I'm a +1 for HCD; it sounds friendlier, and it's inclusive of folks who aren't current users (but who might, someday, become users).

**Comment by jameshupp** [comment]
I am certainly sympathetic to `human` here, and I really like Kate's point about people who aren't currently users but might be. But I worry it also has implications we should, at least, be careful about.

1. `user` very clearly includes people using (there's that word again) assistive technologies to interact with a product. While I don't think `human` excludes them, I wonder if it can't tend to bias us toward prioritizing the smoothest or most frictionless solutions — the ones that hide the machine part of the machine — over of the most widely accessible ones. Is this something we can get a quick gut-check on?

2. `human-centered design` has an air of high-fallutin' to me. If nobody else thinks that, though, by all means ignore this. It's a very impressionistic thing.

3. The industry-specific use of `user` feels like it might be meaningful. Do we _want_ to distinguish by implication that we're talking about software rather than, say, physical objects? I think "No" is a fine answer to this, just want to make sure we're saying so.

**Comment by jameshupp** [comment]
Oh, one more concern: stakeholders with decision-making power related to products we work on do sometimes say things like "Well, I'm a user, too" when we point out discrepancies between how they think about the product and how the audience for it thinks about it. That is an even bigger issue if we only call it "human-centered design." How do we use that term to explain the distinction in which humans we don't actually mean?

Again, I don't mean to say we shouldn't use `HCD` anyway, just want to make sure we're thinking about how it will come up within the context of 18F's and TTS's day-to-day work and whether that'll be a problem.

**Comment by andrewmaier** [comment]
I don't believe 18F benefits from prescribing roles to the people we serve vis. the software or services we design. Human needs must drive our work. It's why we practice plain language: if we can say something more simply, we should — even if "users" are more familiar with jargon (for example, "duty station" vs. "where do you work?")

Additionally, 18F authors our `README.md`, `CONTRIBUTING.md`, etc. files to ensure that technically savvy people can deploy, maintain, and contribute to our open source software (or reuse our products, like the Methods). Developers aren't exactly the target "users" for Methods, but we care about their needs all the same.

**Comment by andrewmaier** [comment]
@jameshupp re: stakeholders and power in the design process, have you seen the Method we're working on on [collaborative design](https://docs.google.com/document/d/167FRZ_2lT5YF4AaJdJFjr5p0p65qvjSozuzpvzrHfDc/edit) and [how we might encourage inclusivity in that process](https://docs.google.com/document/d/1JvffcOmZvae4r0jmLG6epywqMG-w3L-JZiknJ6vBrVk/edit)?

**Comment by wslack** [comment]
I'll +1 what James said. "Human-centered design" obfuscates the need to focus on the needs of the humans who are **using vs making** the service.

I think that HCD is a value that we can and should hold, but the specific transformative practice we are trying to introduce into the vast USG bureaucracy is more accurately and plainly described as "user centered."

**Comment by jeanninehunter** [comment]
Was looking for examples of journey maps I created as a template to help someone I've met doing D&I work in the community with their project, and revisited a VA PDF **(particularly pages 3-6)**  containing info that seemed relevant to this thread: 
http://www.innovation.va.gov/docs/Toward_A_Veteran_Centered_VA_JULY2014.pdf

**Comment by annahsgraves** [comment]
After thinking about this and reading everybody's thoughts, I personally lean towards *user* over *human*. While I adore the Google Trends @abbeykos shared (yay for data!), the implications @jameshupp outlined in https://github.com/18F/content-guide/issues/212#issuecomment-391857561 stick out to me as pretty significant and a strong set of reasons to stick with *user*.

**Comment by andrewmaier** [comment]
Was discussing this thread with my friend Elissa this morning (who works with the USDS at the VA by way of Ad Hoc) and she shared an article with [her rationale in favor of human-centeredness](https://www.eduiconf.org/2017/anything-but-users/).

**Comment by awfrancisco** [comment]
I agree with everything @annahsebok said there. I vote for `user`.

**Comment by awfrancisco** [comment]
We discussed this in the g-content meeting and decided to go with `user-centered design`. We'll add a short not to the specific phrases section to indicate that we prefer `user`. Thanks for the lively discussion!
