### ISSUE TITLE
Issue templates

### ISSUE THREAD

**Issue by awfrancisco** [18F/content-guide#213]
GitHub has a new feature that allows repos to have [multiple issue templates](https://help.github.com/articles/about-issue-and-pull-request-templates/#issue-templates). This repo currently has no templates. 

1. Do we need them? 
2. Would it be helpful to have both a discussion and a bug fix template?

**Comment by annahsgraves** [comment]
Are there any particularly problems we would be solving by creating multiple issue templates? Are we struggling with how current issues are filed?

**Comment by kategarklavs** [comment]
During our guild meeting discussion, we talked about how there aren't any problems (per se) with the current template, but that having two templates might make it easier to track the % of issues that are suggestions (feature requests) and the % that are bug fixes.

**Comment by annahsgraves** [comment]
That's a fair point! That said, my personal sense is that templates are designed to gather more information than a binary categorization. If there's information we feel has been consistently missing from the issues we get, I think updating the templates is a great way to solve for that, but there may be other ways to gather data on the split between suggestions and bug fixes. For example, we could create labels and assign them as issues come in.

**Comment by kategarklavs** [comment]
For sure! That also seems like a good solution 😁

**Comment by awfrancisco** [comment]
Closing since I don't think we have a need for these.
