### ISSUE TITLE
Error on `docker-compose up`

### ISSUE THREAD

**Issue by gall0** [18F/content-guide#217]
Please advice, I get the following error when I try to compose up. 
~~~~
WARNING: The PWD variable is not set. Defaulting to a blank string.
Creating contentguide_ruby_1 ...
Creating contentguide_ci_build_1 ...
Creating contentguide_ci_build_1 ... error

Creating contentguide_ruby_1     ... error
e name is too short, names should be at least two alphanumeric characters'

ERROR: for contentguide_ruby_1  Cannot create container for service ruby: b'create .: volume name is too short, names should be at least two alphanumeric characters'

ERROR: for ci_build  Cannot create container for service ci_build: b'create .: volume name is too short, names should be at least two alphanumeric characters'

ERROR: for ruby  Cannot create container for service ruby: b'create .: volume name is too short, names should be at least two alphanumeric characters'
ERROR: Encountered errors while bringing up the project.
~~~~

**Comment by mgwalker** [comment]
Hi @gall0!  Quick question to help us understand what's going wrong: are you trying to run this on Windows?

**Comment by gall0** [comment]
That is the case. I am using Oracle VM Virtualbox Manager to launch `CentOS Linux release 7.2.1511 (Core)`

**Comment by wslack** [comment]
@gall0 were you able to run on Jekyll instead?

EDIT: We haven't made a special effort to maintain docker compatibility so this may not be something easily resolved. I can state with confidence that the site builds on Jekyll.

**Comment by joelinwood** [comment]
I had the same issue with Docker on my Mac. I'll try Jekyll. This thing is awesome, BTW!

**Comment by brentryanjohnson** [comment]
Closing for now, since we don't (yet) have Docker for the USWDS version of the guide.
