### ISSUE TITLE
Inconsistent use of quotes and italics

### ISSUE THREAD

**Issue by richardcornish** [18F/content-guide#22]
There seems to be an inconsistent use of quotation marks and italics to denote examples, sometimes in the same sentence. For example:

> **and** (never “&” or “+,” unless part of an official title. For example, _D.C. Tech Lady Hackathon + Training Day_)

And other times a character is literally used without special formatting.

> percent is preferred to %. For example, 10 percent of respondents cited. . .

and

> Slash - avoid using /. Replace it with words.

https://pages.18f.gov/content-guide/specific-words-and-phrases/

There should probably be one style used to denote examples throughout the text.

**Comment by jameshupp** [comment]
I've looked through and think we've managed to bring everything in line, so I'm going to close this. We'll keep an eye out for this in future content as we continue to develop the guide.
