### ISSUE TITLE
Words to Avoid:  Implement, Implementation  

### ISSUE THREAD

**Issue by clstmbrly** [18F/content-guide#220]
Some suggested "Words to Avoid":
- Implement
- Implementing
- Implementation

A recent usage example was this section title:  "Implementing a Solution."  The related guide gives the steps needed to design, build, and install a system.  

In some cases, "install" might work for "implement" (as with a system), but implementing a system often includes more than installation.  "Deploy" is often used (for systems), but this too is a word to avoid.  Suggestions welcomed.

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
