### ISSUE TITLE
Add context for choosing "user-centered" over "human-centered"

### ISSUE THREAD

**Issue by juliaklindpaintner** [18F/content-guide#221]
Given the strong feelings in the debate over human- vs. user-centered, it seemed to me that including a bit of context on our decision would help illuminate this choice to both internal and external audiences. 

I suggest changing the bullet point on the Specific Terms and Phrases page to read something like: 

- **user-centered design**, preferred term over human-centered design to describe 18F’s principles and work. This choice is meant to emphasize that design work should be centered around the experience of those who are _using_ a service/product (rather than those making it or humans in general).

I'm sure this wording could be improved!

**Comment by juliaklindpaintner** [comment]
Of course, this comment assumes that we want to stick with the choice of "user-centered" as a preference. If not, I'd be in favor of listing both, like: 

- **user-centered design**, used interchangeably with human-centered design in 18F's principles and work to describe a focus on those those who are _using_ a service/product (rather than those making it or humans in general).

(and I guess you might add another bullet point higher up: 

- **human-centered design**, used interchangeably with "user-centered design" in 18F's principles and work to describe a focus on those those who are _using_ a service/product (rather than those making it or humans in general).
)

**Comment by brentryanjohnson** [comment]
This suggestion was added with #227.
