### ISSUE TITLE
Search results showing a blank entry

### ISSUE THREAD

**Issue by claireblaustein** [18F/content-guide#232]
When searching for "error" the second result turned up as a blank space. 

![image](https://user-images.githubusercontent.com/39384914/74550649-bc4d8980-4f1f-11ea-8494-057c579888e6.png)

**Comment by brentryanjohnson** [comment]
It appears the missing item is a README file. Hypothesis: this file isn't displaying because it lacks front matter, and consequently lacks the `{{ page.title }}` variable.

**Comment by brentryanjohnson** [comment]
This should be resolved with #245
