### ISSUE TITLE
switch to uswds-jekyll

### ISSUE THREAD

**Issue by afeld** [18F/content-guide#234]
This guide is still using the `guides_style_18f` theme, which is deprecated, and isn't compatible with newer versions of Jekyll.

**Comment by brentryanjohnson** [comment]
@afeld The [migration to USWDS is in progress here](https://github.com/18F/content-guide-uswds).

**Comment by afeld** [comment]
Can we do it in a branch rather than have a redundant repository?

**Comment by afeld** [comment]
Also, just did the same migration for Before You Ship, if it's helpful as a reference: https://github.com/18F/before-you-ship/pull/458

**Comment by brentryanjohnson** [comment]
Sure. The content team has been working on this migration ourselves, with no developer support so far. We may need to open a microrequest depending on technical requirements.
