### ISSUE TITLE
Search.gov analytics are not being collected

### ISSUE THREAD

**Issue by jstrothman** [18F/content-guide#257]
Search.gov analytics for the Content Guide only shows data for 9/16 and 9/17.
I _think_ this is because the `site handle` on the site doesn't match the one specified in the Search.gov admin:

- per Search.gov Admin: `content-guide.18f.gov`
- on site: `18f-content-guide`

Screenshot of limited data in Search.gov admin:
![Screen Shot 2021-01-15 at 3 48 42 PM](https://user-images.githubusercontent.com/1080991/104778146-e7051b00-574a-11eb-8781-bd83fe0ab09a.png)

<hr>
Screenshot of site handle spec in Search.gov Admin:
![Screen Shot 2021-01-15 at 3 45 37 PM](https://user-images.githubusercontent.com/1080991/104778217-0308bc80-574b-11eb-8885-70f7f030ba79.png)

<hr>
Screenshot of site handle in the site code:
![Screen Shot 2021-01-15 at 2 56 44 PM](https://user-images.githubusercontent.com/1080991/104778351-35b2b500-574b-11eb-8ae3-3b954f652eec.png)

**Comment by jstrothman** [comment]
@brentryanjohnson Would you like me to confirm this is the issue with Search.gov folks?

**Comment by brentryanjohnson** [comment]
Oof. I thought I fixed this. I'll look into it! Thank you, @jstrothman

**Comment by brentryanjohnson** [comment]
🤔 
<img width="697" alt="18F content guide settings with site handle 18f-content-guide" src="https://user-images.githubusercontent.com/32855580/104780415-9df69c00-5735-11eb-8432-b9c40299ccfc.png">

![config file showing search site handle as 18f-content-guide](https://user-images.githubusercontent.com/32855580/104780417-9f27c900-5735-11eb-8a4b-0f1e3fe94642.png)

**Comment by jstrothman** [comment]
weird
![Screen Shot 2021-01-15 at 3 45 37 PM](https://user-images.githubusercontent.com/1080991/104780896-83312100-574f-11eb-9066-04808f460951.png)

**Comment by brentryanjohnson** [comment]
Resolved
