### ISSUE TITLE
Years

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/content-guide#26]
'90s for 1990s. Likely for specific words and phrases section.

**Comment by awfrancisco** [comment]
That sounds a little informal to me, even for a blog post. Definitely wouldn't recommend it for product content.

**Comment by emileighoutlaw** [comment]
We've already done it the first FEC API post ("since opening its doors in the '70s"), and it's also in the TBT post. I can definitely see some informal decades coming up in future TBT blog posts. Happy to ban if other people agree.

**Comment by kategarklavs** [comment]
Would it be appropriate to recommend full years in most cases, but note that less formal contexts (blog posts) warrant the abbreviated version?

I'm a fan of the abbreviated version in more casual instances, but it might seem weird in other contexts (tax forms, official applications, etc.).

**Comment by awfrancisco** [comment]
Maybe it would be better to frame it as a permission instead of a guideline. If you feel the need in an informal context to use '90, then we aren't going to edit you back to using 1990. But I don't think we should recommend that people choose '90 over 1990.

**Comment by kategarklavs** [comment]
Thumbs up to this.
