### ISSUE TITLE
Voice and tone uses the word "tone-deaf"

### ISSUE THREAD

**Issue by chylu** [18F/content-guide#263]
The guidelines for _Inclusive language_ state:

> Avoid terms that contribute to stigmas around sensory disabilities: _blind spot_ or _tone deaf_.
- https://content-guide.18f.gov/our-style/inclusive-language/

However, the _Voice and tone_ section goes on to say:

> Instead of picking up on your nonverbal — or perhaps verbal — cues, this associate is **tone-deaf**.
- https://content-guide.18f.gov/our-style/voice-and-tone/
(The phrase is even bolded on the page!)

I think this problematic phrase might be best addressed by making the passage more concise.

From:
> As we mentioned earlier, your voice is a constant, but your tone is a variable. Consider the following: If you’re having an irredeemably terrible day, you might get peeved at a store associate who chirpily (and repeatedly) asks if they can help you with anything. Instead of picking up on your nonverbal — or perhaps verbal — cues, this associate is **tone-deaf**. The associate maintained a consistently helpful voice, but they failed to shift their tone from energetic to restrained. As a result, their message (however valuable or well-intended) is lost on you.

To:
> As we mentioned earlier, your voice is a constant, but your tone is a variable. Consider the following: If you’re having an irredeemably terrible day, you might get peeved at a store associate who chirpily (and repeatedly) asks if they can help you with anything. While the associate maintained a helpful voice, they failed to shift from an energetic to a restrained tone based on the situation. As a result, their message (however valuable or well-intended) is lost on you.

**Comment by brentryanjohnson** [comment]
Excellent catch. Thank you, @chylu.
