### ISSUE TITLE
Fiscal Year

### ISSUE THREAD

**Issue by awfrancisco** [18F/content-guide#28]
Guidance on capitalization and whether abbreviation is ok.

**Comment by nicoleslaw** [comment]
AP says "fiscal year" and, "We would spell out fiscal year on second reference, as it is not a generally recognized abbreviation. (But, if you do use it, it would be FY 2006.)"

What do you think of going with that?

**Comment by kategarklavs** [comment]
+1 to this (and I'm OK with using _FY_ as an abbreviation, too).
