### ISSUE TITLE
Asian American Journalists Association Handbook - content not available

### ISSUE THREAD

**Issue by markXLIX** [18F/content-guide#283]
https://content-guide.18f.gov/our-style/inclusive-language/ 
Section: Media style guides for race, ethnicity, and religion
Link to Asian American Journalists Association Handbook points to a AAJA page without content.

According to [this page](https://www.aaja.org/2020/11/30/guide-to-covering-asian-pacific-america/) the new handbook is under development as of 2021-12-01.  I cannot find mention of it on the AAJA site since.  

They do point to [this page](https://consciousstyleguide.com/) as a fallback in the meantime.  Perhaps the Content Guide page could be updated to reflect this situation and provide a direct link to somewhere within?

**Comment by michelle-rago** [comment]
Thanks for flagging! I like the idea of updating the link to https://www.aaja.org/2020/11/30/guide-to-covering-asian-pacific-america/ to reflect the current situation (which includes the link to the Conscious Style Guide, as you mentioned).

**Comment by michelle-rago** [comment]
On second thought, we'll link to https://www.aaja.org/news-and-resources/guidances/ for now. Thanks again for letting us know!!
