### ISSUE TITLE
Use of stock imagery

### ISSUE THREAD

**Issue by jameshupp** [18F/content-guide#29]
If ever, when do we/when don't we? What makes it good/not good?

**Comment by nicoleslaw** [comment]
@jameshupp Would this make more sense for the branding team, or are you thinking of partner projects?

**Comment by jameshupp** [comment]
@nicoleslaw I was mostly thinking about our own content. I think the branding work has overtaken this issue and is a better place to manage this, but I also think my concern was premature anyway. I'd be fine with closing this as a wontfix as long as someone else concurs.

**Comment by brittag** [comment]
We have a teeeny bit of advice for this at https://handbook.18f.gov/design/#assets - at least on the level of "try to use US gov public domain images".

**Comment by brittag** [comment]
In other words, I concur with closing this as wontfix + probably adding any guidance over on that design page.
