### ISSUE TITLE
Project names

### ISSUE THREAD

**Issue by awfrancisco** [18F/content-guide#30]
Guidance on capitalization and general constructions of project names. For instance, do we prefer "openFOIA" or "OpenFEC."

**Comment by jameshupp** [comment]
We should probably distinguish between choices we get to make by our lonesome and choices made with a partner agency. Seems worth an extra sentence to carve out time for respecting the partner's style when it's a project for them.

**Comment by awfrancisco** [comment]
Yeah. This is a tricky guidance. Obviously, if a partner agency has a set name we should go with it, but if we're involved in the branding, what are our capitalization guidelines and other naming conventions? Would we let an agency do something super governmental like The Consolidated Office of Lawn Mower Operators and Technicians? Would we object to Silicon Vally naming conventions like Mowr? This is a larger branding style question that might need to include ideas from project leads. 

For now, we could just add specific guidance on 18F project names that are non-obvious.

**Comment by nicoleslaw** [comment]
@awfrancisco Do we have a list of project names somewhere? Happy to incorporate them into the guide.

**Comment by awfrancisco** [comment]
I think Mel made a list as part of her Dashboard work, but we'll have to dig up that link. Beyond a list of the correct way to write current projects (which I think is a good MVP), I think we should also add some guidance for when 18F teams name their own projects. But that could be a separate issue.

**Comment by kategarklavs** [comment]
10/19/16 -- In _Specific Words and Phrases_, we could add a _Projects_  subsection (how we treat product/project names).

**Comment by kategarklavs** [comment]
As discussed during our 10/19 meeting, we'll (as a guild) create a list this week of project/product capitalizations and review at our next meeting.

**Comment by emileighoutlaw** [comment]
This feels like it might find a better home in the 18F site. Passing off to @coreycaitlin
