### ISSUE TITLE
Include note for why we differ from GPO

### ISSUE THREAD

**Issue by melodykramer** [18F/content-guide#38]
We can use this, if you'd like:

Although we are aware of the GPO, we used AP as a basis for our style guide. We decided to use lower case lettering for a few reasons:
1. We feel that readers are slowed down by capital words. So even if we contradict the GPO,`federal government` is ultimately more friendly and faster to read and comprehend.
2. We took some inspiration from this plain language page and then adapted it. As I remember, the basic motivation was that big official capital Federal Government was uninviting and unnecessary. There’s only one federal government and we couldn't think of an example when the federal government would not be operating in an official capacity. 
3. GPO's mission is producing 'the official information products of the U.S. Government.' GPO's style may govern for official information, but we think it's preferable for the rest of us to favor readability over officialness.

**Comment by jameshupp** [comment]
We might want to be more explicit that our mission is making government technology better as a tool of public service.

Digital content should be useful and usable. Opting for lower-case `federal governmentIt's not necessarily more _useful_, but things can be useful in different ways. Usefulness as a record is one thing, and being as official as possible helps for that. But in many cases, what makes our content most useful is how much it helps the general public interact with the government. Lower cased `federal government` is more readable and inviting.
