### ISSUE TITLE
Sticky Notes

### ISSUE THREAD

**Issue by Scotchester** [18F/content-guide#4]
The information on Sticky Notes on the ["Specific words and phrases"](https://pages.18f.gov/content-guide/specific-words-and-phrases/) page is incorrect. The [trademark](http://tmsearch.uspto.gov/bin/showfield?f=doc&state=4807:ven4mr.2.12) applies to "pads of adhesive-backed paper notes".

**Comment by awfrancisco** [comment]
Thanks for the heads up. We are going to remove that section from Specific words and phrases and transfer the guidance to a new, expanded section on Trademarks and brands. That section should be live this week.

**Comment by Scotchester** [comment]
:+1:

**Comment by awfrancisco** [comment]
The new section is live 
https://pages.18f.gov/content-guide/trademarks-and-brands/
