### ISSUE TITLE
Add more simple word choices

### ISSUE THREAD

**Issue by awfrancisco** [18F/content-guide#46]
Go through this list and see if we should adopt any of these for our list of words to avoid. 

http://www.kingcounty.gov/exec/styleguide/concisewriting/simplerwords.aspx

**Comment by coreycaitlin** [comment]
We're going to link to this resource, instead of duplicating.

**Comment by coreycaitlin** [comment]
(See also #78 & #77)

Our goal: to link to plain language lists instead of maintaining the One True List.

**Comment by coreycaitlin** [comment]
Closing this out — I included this link in #112
