### ISSUE TITLE
Idea: Add guidance on when to style words as code, and when to leave them styled as paragraph text. 

### ISSUE THREAD

**Issue by carodew** [18F/content-guide#57]
It could look like this: 

"Group each set of thematically related controls in a `fieldset` element. Use the `legend` element to offer a label within each one. The `fieldset` and `legend` element makes it easier for screen reader users to navigate the form.” 

Or like this:

"Group each set of thematically related controls in a fieldset element. Use the legend element to offer a label within each one. The fieldset and legend element makes it easier for screen reader users to navigate the form.” 

Could include guidance relating to how technical the audience is, is the code snippet going to be copied and pasted, and how jarring it is to read the content with a lot of `code` stylings.

**Comment by tadhg-ohiggins** [comment]
I think this issue is addressed by: https://pages.18f.gov/content-guide/technical-and-interface-writing/#code so I'm closing it. We can open new issues if we have suggestions for changes.
