### ISSUE TITLE
Clarify capitalization of URLs in non-narrative contexts

### ISSUE THREAD

**Issue by jameshupp** [18F/content-guide#58]
I think we want them to be lowercased everywhere unless there's a native style (to someone else's URL) that is CamelCase or something like that. But we should just get really clear about this and, more importantly, _why_. (I continue to be antsy about the content guide becoming a list of things rather than principles and reasons behind the things.

**Comment by kategarklavs** [comment]
@jameshupp Totally agree that the guide should not be a list of things, but rather things + the principles underlying them. Also in full agreement re: lowercasing URLs.

**Comment by tadhg-ohiggins** [comment]
The URLs and filenames section has this: “Whether beginning with the protocol or not, always lowercase URLs in text. Paths are case-sensitive, however, so their casing must be preserved.” Is that sufficient to close this issue?
