### ISSUE TITLE
Use consistent section headings

### ISSUE THREAD

**Issue by nicoleslaw** [18F/content-guide#59]
The headings within the guide switch between topics (nouns) and directives (verb phrases). We could clean this up a bit and make it more scannable (happy to do it, just logging for now).

**Comment by awfrancisco** [comment]
I think that's a great suggestion. I think our general heading style favors directives, but I'm fine with going either way for the guide.

**Comment by tadhg-ohiggins** [comment]
Some of these are difficult to fix, but how about changing
“Optimize headings and titles” to “Headings and titles”
and
“Publishing legal and technical content” to “Legal and technical content”? Happy to submit a PR if those sound like reasonable changes.

**Comment by nicoleslaw** [comment]
Sounds good to me @tadhg-ohiggins -- happy to help here as well later this week. Let me know if you want to chat through together!
