### ISSUE TITLE
Typo/Grammar issues

### ISSUE THREAD

**Issue by OriHoffer** [18F/content-guide#6]
"This guide takes into account that frustration as well as several commonly..."
- Should be "This guide takes that frustration into account, as well as several..."

"make a copy of this document and adapt its to your organizational needs."
- Should be 'it' not 'its'

**Comment by awfrancisco** [comment]
Fixed https://github.com/18F/content-guide/commit/228b73bc4071a0b6fed0e6ec8e1e6d065615cfd7
