### ISSUE TITLE
Add section on guidance on writing for limited English proficiency users

### ISSUE THREAD

**Issue by awfrancisco** [18F/content-guide#70]
This is a goal in the National Action Plan. 
https://18f.slack.com/files/gregboone/F0DBY6YFJ/screen_shot_2015-10-28_at_10.00.31_am.png

**Comment by emileighoutlaw** [comment]
Completion criteria:
- [ ] Research
- [ ] Share findings with team
(after that, we'll open a new issue for implementation)

**Comment by coreycaitlin** [comment]
@kategarklavs Would this be a good candidate for a pairing session? Seems like it might be nice to find sources and main arguments in conversation.

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
