### ISSUE TITLE
Revise and expand "Conscious language" guidance

### ISSUE THREAD

**Issue by awfrancisco** [18F/content-guide#72]
Add something about ableist language along these lines? 
https://twitter.com/lizduckchong/status/655952122484101120

**Comment by brittag** [comment]
This reminds me of GOV.UK's guidance about [inclusive communication](https://www.gov.uk/government/publications/inclusive-communication) - it's more about [how to write about people with disabilities in a respectful way](https://www.gov.uk/government/publications/inclusive-communication/inclusive-language-words-to-use-and-avoid-when-writing-about-disability). I think the content guide could include both angles.

**Comment by jeanninehunter** [comment]
Started to create list as part of work for spring IRL as well as diversity working group listening tour and subsequent ideation. Will share tentative list for ablest/diversity/inclusive language soonest.

**Comment by emileighoutlaw** [comment]
ping @jeanninehunter

**Comment by jeanninehunter** [comment]
Whew, it appears the interest arose a year ago, but work on this, in earnest, took place within the last few months, so we'll move forward on this and thanks for the reminder at the latest guild meeting, @emileighoutlaw!

**Comment by jeanninehunter** [comment]
Find [attached copy](https://docs.google.com/a/gsa.gov/document/d/1Xj7v57zI9A7pO_6dUX3CwaYiVbDsU-f1vlm84Cjnn4s/edit?usp=sharing) that reflects insight gleaned from the work of some of our Diversity Guild members regarding ability/disability, age, gender, and other topics; different style guides that offer information on specific words/phrases as well as existing definitions/texts contained in our 18F Content Guide.

**Comment by emileighoutlaw** [comment]
Next steps:
- [x]  Content team to review Jeannine's draft (for content completeness and copyediting) during content workshop!
- [x] Implementation

**Comment by emileighoutlaw** [comment]
Jeannine will bring to XD workshop tomorrow! (2/2/17) 🎉

**Comment by coreycaitlin** [comment]
@jeanninehunter Hello! Any update on this? Would it be useful to pair on revision and moving this into markdown?

**Comment by jeanninehunter** [comment]
@coreycaitlin Received feedback in February from content and diversity guild members. Sure, we could revise in tandem and move into markdown.

**Comment by jeanninehunter** [comment]
@coreycaitlin and I wordsmithed the draft during a content pairing session; we're scheduIed to meet again next week to compIete it.

**Comment by coreycaitlin** [comment]
Changed the name of the issue to better reflect the full scope of work we wound up tackling on this page.

This content is ready for one more review before we move it to markdown: [Draft here (limited access)](https://docs.google.com/document/d/1Xj7v57zI9A7pO_6dUX3CwaYiVbDsU-f1vlm84Cjnn4s/edit)

**Comment by nicoleslaw** [comment]
@jeanninehunter @coreycaitlin Thank you so much for taking the time to expand and refine this section of the guide! This looks great. I added some minor suggestions and additions.

**Comment by jeanninehunter** [comment]
@nicoleslaw Really appreciated the time and sensitivity @coreycaitlin exhibited as we parsed definitions/style suggestions. Also, agree with the suggestions you and @RyanSibley are making in the doc.

**Comment by coreycaitlin** [comment]
Next step: @coreycaitlin to resolve suggestions/comments, and move to Markdown.

**Comment by nicoleslaw** [comment]
Any updates on this? I would like to share it with the USAGov folks.

**Comment by jeanninehunter** [comment]
thx @nicoleslaw for pinging me about this; adding it to top of to-do list! also appreciate all of @coreycaitlin's hard work!

**Comment by jeanninehunter** [comment]
While #g-content discussed different content guide issues, I noticed this one was still open. Closing since [this content](https://content-guide.18f.gov/inclusive-language/) was published fall 2017.
