### ISSUE TITLE
More alternative options on plain language page?

### ISSUE THREAD

**Issue by wslack** [18F/content-guide#77]
From https://twitter.com/rseymour/status/669262489549414402, a request for more alternatives on https://pages.18f.gov/content-guide/plain-language/. FWIW, this would also help me. :)

**Comment by quepol** [comment]
http://www.plainlanguage.gov/howto/guidelines/FederalPLGuidelines/writeNoJargon.cfm
https://insidegovuk.blog.gov.uk/2014/04/11/avoiding-words-to-avoid/
https://www.gov.uk/guidance/style-guide/a-to-z-of-gov-uk-style#words-to-avoid
https://www.gov.uk/guidance/content-design/writing-for-gov-uk#plain-english

**Comment by emileighoutlaw** [comment]
Thanks for this issue, folks!

We've merged more word choices and guidance/links. 

We'll close this issue, but feel free to open more issues to request additional words and outside resources!
