### ISSUE TITLE
Plain Language Ideas from the Thanksgiving Table

### ISSUE THREAD

**Issue by wslack** [18F/content-guide#78]
For https://pages.18f.gov/content-guide/plain-language/

Modify > Change
~~Perform > Do~~
~~Purchase > Buy~~
~~Terminate > End~~
Navigate To > Go To
Image > Picture
Toggle > Switch
Obtain > Get
Configure > Set up
Execute > Run
Halt > Stop
Value > Number

**Comment by tadhg-ohiggins** [comment]
Summary of #g-content feelings about these suggestions as of 2016-06-13:
-   Deprecate “modify” and recommend using “change” instead.
-   Do not add the “perform” to “do” recommendation as “perform” is appropriate in many cases.
-   Do not add the “purchase” to “buy” recommendation as “purchase” is appropriate in many cases.
-   Do not add the “terminate” to “end” recommendation as “terminate” is appropriate in many cases.

It's possible that we might want to add a set of softer recommendations for cases like the last three above, where the word is fine in certain cases but probably shouldn't be used where the alternative has the same intended meaning.

I'll keep asking about these periodically in Slack until we've gone through the list, then add PRs and/or new issues.

**Comment by wslack** [comment]
edited per ^^

**Comment by coreycaitlin** [comment]
The PR above includes:
- Modify (use _change_ instead)
- Execute (use _run_ or _do_)

The rest of these feel like they'd need a bit more thought.

**Comment by emileighoutlaw** [comment]
We merged in a handful of the requested changes. The others we aren't ready to add at this time, so I'm going to close this issue. As always, thanks for contributing(!), and please do feel free to open more issues if you think of other words and phrases you might like to add to our guide.
