### ISSUE TITLE
Add a section or guide about content research/testing

### ISSUE THREAD

**Issue by kategarklavs** [18F/content-guide#8]
@khandelwal also suggested including a research/testing section in the Content Guide. This could take the form of a new section, or it could be its own guide. (We discussed this briefly during the blog huddle — topic warrants further discussion.)

cc @jeanninehunter @awfrancisco @emileighoutlaw @gboone

**Comment by nicoleslaw** [comment]
@emileighoutlaw @awfrancisco I am happy to take a shot at this— @kategarklavs mentioned you had some preliminary text about content testing. Could you point me to that?

**Comment by awfrancisco** [comment]
Is it this blog post? https://18f.gsa.gov/2016/04/19/looking-at-the-different-ways-to-test-content/

**Comment by emileighoutlaw** [comment]
Yes! It's the blog post. There's also an 18F Edu module, but I think the blog post covers most of the same stuff.

**Comment by kategarklavs** [comment]
Ping!

**Comment by coreycaitlin** [comment]
Closing this issue out, since we have [a start to this content](https://content-guide.18f.gov/keep-refining/#testing-and-ongoing-research) on the "Keep refining" page. If we feel there's need for more in-depth guidance, let's open a new issue for that!
