### ISSUE TITLE
Find a good place to link the 18F Open Source Style Guide

### ISSUE THREAD

**Issue by brittag** [18F/content-guide#89]
https://pages.18f.gov/open-source-guide/ is essentially a content guide for open source projects, including writing good readmes. We should find a nice visible way to integrate a link into this guide.

Thought experiment: we could even consider merging the two guides, since a decent-sized chunk of 18F content is open source project content.

**Comment by tadhg-ohiggins** [comment]
Linked to in “Publishing legal and technical content”, closing.
