### ISSUE TITLE
Add mention of Hemingway App 

### ISSUE THREAD

**Issue by kategarklavs** [18F/content-guide#9]
@khandelwal suggested that we might mention the Hemingway App in the Content Guide — adding an issue as a reminder to add a small section about the app.

**Comment by llolly** [comment]
llolly2000@hotmail.com

**Comment by kategarklavs** [comment]
The Handbook has a section on text editors -- during our 6/1/6 guild meeting, we all agreed that publishing this in the Content Guide would be duplicative. Closing this issue for now!
