### ISSUE TITLE
broken link in EITI example

### ISSUE THREAD

**Issue by coreycaitlin** [18F/content-guide#92]
In this paragraph on the "Optimize headings and titles" page, the example is outdated and the link goes to a 404 page:

> For example, an interior page on the U.S. EITI site is titled “U.S. Natural Resource Sectors.” Before naming a page like this, you should compare the phrase “natural resources” to similar phrases like “natural deposits.” A Google Trend search comparing those two phrases, shows that “natural resources” is a much more popular search term.

...while this is a great reminder to revisit EITI keywords, that page no longer exists. Happy to fix this, but wanted to note it so I don't forget.

**Comment by awfrancisco** [comment]
@gboone could you maybe help in finding where this page went? Or finding a new one?

**Comment by gboone** [comment]
HMMM, I'll look into it. I'm thinking maybe that was on the old EITI site, but not sure.

**Comment by nicoleslaw** [comment]
@coreycaitlin I think the example is useful—what do you think of reframing it like, "if you were thinking about titling a section x, consider searching for similar terms like y..."

**Comment by tadhg-ohiggins** [comment]
AFAICT this was fixed by https://github.com/18F/content-guide/pull/113, so I'm closing it. Re-open if you have objections.
